# Debug script for PhantomOS with pc board.

assert_spec x86

create_boot_directory
build {
	core init timer
	lib/ld lib/vfs
	driver/platform
	driver/acpi
	driver/ahci
	driver/rtc
	app/pci_decode
	server/report_rom
	server/nitpicker
  server/vfs
  snapper
  lib/vfs_lwext4
  lib/snap

  server/tcp_terminal lib/libc lib/libm
  driver/uart
}

import_from_depot [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/gui_fb \
                  [depot_user]/src/init \
                  [depot_user]/src/sandbox \
                  [depot_user]/src/monitor

#
# Build EXT4-file-system image
#
set mke4fs [installed_command mkfs.ext4]
set dd     [installed_command dd]

catch { exec $dd if=/dev/zero of=bin/block0.raw bs=1M count=0 seek=2048 }
catch { exec $dd dd conv=notrunc bs=4096 count=1 seek=16 if=/phantomuserland/src/run/img/phantom.superblock of=bin/block0.raw }

catch { exec $dd if=/dev/zero of=bin/snapper_block.raw bs=1M count=256 }
catch { exec $mke4fs -O^metadata_csum -F bin/snapper_block.raw }

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer" priority="0">
		<resource name="RAM" quantum="1M"/>
		<resource name="CPU" quantum="5"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="pc_rtc">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Rtc"/>
		</provides>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config>
			<policy label="pci_decode -> system"    report="acpi -> acpi"/>
			<policy label="platform -> devices" report="pci_decode -> devices"/>
		</config>
	</start>

	<start name="acpi" caps="350">
		<resource name="RAM" quantum="4M"/>
		<route>
			<service name="Report"> <child name="report_rom"/> </service>
			<service name="IO_MEM"> <parent/> </service>
			<service name="LOG">    <parent/> </service>
			<service name="PD">     <parent/> </service>
			<service name="RM">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
			<service name="ROM">    <parent/> </service>
		</route>
	</start>

	<start name="pci_decode" caps="350">
		<resource name="RAM" quantum="2M"/>
		<route>
			<service name="Report">             <child name="report_rom"/> </service>
			<service name="ROM" label="system"> <child name="report_rom"/> </service>
			<service name="IO_MEM"> <parent/> </service>
			<service name="LOG">    <parent/> </service>
			<service name="PD">     <parent/> </service>
			<service name="RM">     <parent/> </service>
			<service name="CPU">    <parent/> </service>
			<service name="ROM">    <parent/> </service>
		</route>
	</start>

	<start name="platform" caps="100" managing_system="yes">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Platform"/>
		</provides>
		<route>
			<service name="ROM" label="devices"> <child name="report_rom"/> </service>
			<service name="Report"> <child name="report_rom"/> </service>
			<service name="IRQ">     <parent/> </service>
			<service name="IO_MEM">  <parent/> </service>
			<service name="IO_PORT"> <parent/> </service>
			<service name="ROM">     <parent/> </service>
			<service name="PD">      <parent/> </service>
			<service name="CPU">     <parent/> </service>
			<service name="LOG">     <parent/> </service>
			<service name="Timer">   <child name="timer"/> </service>
		</route>
		<config>
			<report devices="yes"/>
			<policy label="ahci -> "> <pci class="AHCI"/> </policy>
		</config>
	</start>

	<start name="ahci_report_rom">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes"/>
	</start>

	<start name="ahci">
		<resource name="RAM" quantum="1M" />
		<provides><service name="Block" /></provides>
		<config atapi="no">
			<report ports="yes"/>
			<policy label="monitor -> isomem -> " device="0" writeable="yes" />
			<policy label="vfs -> " device="1" writeable="yes" />
		</config>
		<route>
			<service name="Report"> <child name="ahci_report_rom"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	<start name="drivers" caps="1500" ram="120M" managing_system="yes">
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer">   <child name="timer"/> </service>
			<service name="Capture"> <child name="nitpicker"/> </service>
			<service name="Event">   <child name="nitpicker"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nitpicker" ram="4M">
		<provides>
			<service name="Gui"/> <service name="Capture"/> <service name="Event"/>
		</provides>
		<config>
			<capture/> <event/>
			<domain name="default" layer="1" content="client" label="no" hover="always" focus="click" width="1024" height="768"/>

			<default-policy domain="default"/>
		</config>
		<route> <any-service> <parent/> <any-child/> </any-service> </route>
	</start>

  <start name="vfs" ram="200M" caps="200">
   	<provides><service name="File_system"/></provides>
   	<config>
   		<vfs>
   			<dir name="dev">
   				<block name="block" block_buffer_count="128"/>
   			</dir>
        <lwext4 block_device="/dev/block" cache_write_back="yes"
              expand_via_io="no" writeable="yes"
              reporting="no"
              external_cache_size="32M" report_cache="yes"/>
   		</vfs>
   		<policy label_prefix="snapper" root="/" writeable="yes"/>
   	</config>
    <route>
      <service name="Block"><child name="ahci"/></service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
  </start>

  <start name="snapper" ram="400M" caps="100">
    <provides>
      <service name="Snapper"/>
    </provides>

    <config
        verbose="true"
        redundancy="2"
        integrity="true"
        max_snapshots="0"
        min_snapshots="0"
        threshold="1000"
        expiration="3600">

      <rtc/>

      <vfs>
        <fs/>
      </vfs>
    </config>
	<route>
		<service name="Block"><child name="ahci"/></service>
		<any-service> <parent/> <any-child /> </any-service>
	</route>
  </start>

  <start name="terminal" ram="2M">
		<binary name="pc_uart"/>
		<provides>
			<service name="Terminal"/>
			<service name="Uart"/>
		</provides>
		<config>
			<policy label_prefix="monitor" uart="1"/>
		</config>
	</start>

  <start name="monitor" caps="4000" ram="2G">
		<config>
			<parent-provides>
				<service name="LOG"/>
				<service name="PD"/>
				<service name="CPU"/>
        <service name="ROM"/>
        <service name="RM"/>
        <service name="Timer"/>
        <service name="Block"/>
        <service name="Snapper"/>
        <service name="Gui"/>
        <service name="Capture"/>
        <service name="Event"/>
			</parent-provides>
			<default caps="100"/>

			<monitor>
				<policy label="isomem" wait="yes" wx="yes"/>
			</monitor>

    	<start name="isomem" caps="2000">
    		<resource name="RAM" quantum="1G"/>
    
    		<config verbose="yes" ld_verbose="yes">
    		</config>
    		<route>
    			<service name="Block"><parent/></service>
					<service name="PD">  <local/> </service>
					<service name="CPU"> <local/> </service>
    			<any-service> <parent/> <any-child /> </any-service>
    		</route>
    	</start>

		</config>
    <route>
      <service name="Block"><child name="ahci"/></service>
      <service name="Terminal"><child name="terminal"/></service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
	</start>

</config> }

#
# Boot modules
#
build_boot_image [list {*}[build_artifacts] phantom_classes isomem]

append qemu_args " -smp 2 "
append qemu_args " -m 10000 "
append qemu_args " -device ahci,id=ahci -boot d "
append qemu_args " -drive id=disk,file=bin/block0.raw,format=raw,if=none             -device ide-hd,drive=disk,bus=ahci.0 "
append qemu_args " -drive id=snapper,file=bin/snapper_block.raw,format=raw,if=none   -device ide-hd,drive=snapper,bus=ahci.1 "

set host "localhost"
set port "5555"

append qemu_args " -serial stdio "
append qemu_args " -serial chardev:uart "
append qemu_args " -chardev socket,id=uart,port=$port,host=$host,server=on,wait=off,ipv4=on "

run_genode_until forever

# Local Variables:
# mode: tcl
# End:
