# PhantomOS run script.

assert_spec x86

create_boot_directory

set build_components {
    core init timer
    lib/ld lib/vfs
    driver/rtc
    server/nitpicker
    server/vfs
    snapper
    lib/vfs_lwext4
    lib/snap
}

#
# Build EXT4-file-system image
#

set mke4fs [installed_command mkfs.ext4]
set dd     [installed_command dd]
set cat     [installed_command cat]

catch { exec $dd if=/dev/zero of=bin/block0.raw bs=1M count=0 seek=2048 }
catch { exec $dd dd conv=notrunc bs=4096 count=1 seek=16 if=/phantomuserland/src/run/img/phantom.superblock of=bin/block0.raw }

# NB: Change the value of count if you need more space for snapshots.
catch { exec $dd if=/dev/zero of=bin/snapper_block.raw bs=1M count=256 }
catch { exec $mke4fs -O^metadata_csum -F bin/snapper_block.raw }

set config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer" priority="0">
		<resource name="RAM" quantum="1M"/>
		<resource name="CPU" quantum="5"/>
		<provides><service name="Timer"/></provides>
	</start>
}

append config [ exec $cat [genode_dir]/repos/ports/run/phantom_gui-common.inc ]

if {[have_board linux]} {
    lappend build_components server/lx_fs server/vfs_block
    append config [ exec $cat [genode_dir]/repos/ports/run/phantom-linux.inc ]
}

if {[have_board pc]} {
    lappend build_components driver/platform driver/acpi driver/ahci app/pci_decode server/report_rom
   append config [ exec $cat [genode_dir]/repos/ports/run/phantom-pc.inc ]
}

append config { </config> }

build $build_components

import_from_depot [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/gui_fb

install_config $config

#
# Boot modules
#
if {[have_board linux]} {
    build_boot_image [list {*}[build_artifacts] phantom_classes isomem snapper_block.raw block0.raw]
}

if {[have_board pc]} {
    build_boot_image [list {*}[build_artifacts] phantom_classes isomem ]

    append qemu_args " -smp 2 "
    append qemu_args " -m 8000 "
    append qemu_args " -device ahci,id=ahci -boot d "
    append qemu_args " -drive id=disk,file=bin/block0.raw,format=raw,if=none             -device ide-hd,drive=disk,bus=ahci.0 "
    append qemu_args " -drive id=snapper,file=bin/snapper_block.raw,format=raw,if=none   -device ide-hd,drive=snapper,bus=ahci.1 "
}

run_genode_until forever

# Local Variables:
# mode: tcl
# End:
