# Debug script for PhantomOS with pc board.

assert_spec x86

create_boot_directory
build {
    core init timer
    lib/ld lib/vfs
    driver/platform
    driver/acpi
    driver/ahci
    driver/rtc
    app/pci_decode
    server/report_rom
    server/nitpicker
    server/vfs
    snapper
    lib/vfs_lwext4
    lib/snap
    lib/vfs_rump      

    server/tcp_terminal lib/libc lib/libm
    driver/uart
}

import_from_depot [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/src/rom_filter \
                  [depot_user]/src/nit_focus \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/global_keys_handler \
                  [depot_user]/src/gui_fb \
                  [depot_user]/src/init \
                  [depot_user]/src/sandbox \
                  [depot_user]/src/monitor

#
# Build EXT4-file-system image
#
set mke4fs [installed_command mkfs.ext4]
set mke2fs [installed_command mke2fs]
set dd     [installed_command dd]
set cat    [installed_command cat]


catch { exec $dd if=/dev/zero of=bin/block0.raw bs=1M count=0 seek=2048 }
catch { exec $dd dd conv=notrunc bs=4096 count=1 seek=16 if=/phantomuserland/src/run/img/phantom.superblock of=bin/block0.raw }

# NB: Change the value of count if you need more space for snapshots.
catch { exec $dd if=/dev/zero of=bin/snapper_block.raw bs=1M count=256 }
catch { exec $mke4fs -O^metadata_csum -F bin/snapper_block.raw }

# Block storage for file-system that is accessible by userspace.
catch { exec $dd if=/dev/zero of=bin/isomem_fs_block.raw bs=1M count=256 }
catch { exec $mke2fs -F bin/isomem_fs_block.raw }


set config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer" priority="0">
		<resource name="RAM" quantum="1M"/>
		<resource name="CPU" quantum="5"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="pc_rtc">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Rtc"/>
		</provides>
	</start>

  <start name="report_rom">
  	<resource name="RAM" quantum="2M"/>
  	<provides> <service name="Report"/> <service name="ROM"/> </provides>
  	<config>
  		<policy label="pci_decode -> system"    report="acpi -> acpi"/>
  		<policy label="platform -> devices" report="pci_decode -> devices"/>
  		<policy label="usb_hid -> report"    report="usb -> devices"/>
  	</config>
  </start>

  <start name="acpi" caps="350">
  	<resource name="RAM" quantum="4M"/>
  	<route>
  		<service name="Report"> <child name="report_rom"/> </service>
  		<any-service> <parent/> <any-child /> </any-service>
  	</route>
  </start>
  
  <start name="pci_decode" caps="350">
  	<resource name="RAM" quantum="2M"/>
	<route>
  		<service name="Report">             <child name="report_rom"/> </service>
  		<service name="ROM" label="system"> <child name="report_rom"/> </service>
  		<any-service> <parent/> <any-child /> </any-service>
  	</route>
  </start>
  
  <start name="platform" ram="300M" caps="200" managing_system="yes">
  	<provides>
  		<service name="Platform"/>
  	</provides>
  	<route>
  		<service name="ROM" label="devices"> <child name="report_rom"/> </service>
  		<service name="Report"> <child name="report_rom"/> </service>
  		<any-service> <parent/> <any-child /> </any-service>
  	</route>
  	<config>
  		<report devices="yes"/>
  		<policy label="ahci -> "> <pci class="AHCI"/> </policy>
  		<policy label_prefix="ps2"> <device name="ps2"/> </policy>
  		<policy label_prefix="fb"  info="yes"> <pci class="VGA"/> </policy>
  		<policy label_prefix="usb" info="yes"> <pci class="USB"/> </policy>
  	</config>
  </start>

	<start name="ahci_report_rom">
		<binary name="report_rom"/>
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes"/>
	</start>

	<start name="ahci">
		<resource name="RAM" quantum="10M" />
		<provides><service name="Block" /></provides>
		<config atapi="no">
			<report ports="yes"/>
			<policy label="monitor -> isomem -> " device="0" writeable="yes" />
      <policy label="snapper_vfs -> " device="1" writeable="yes" />
      <policy label="isomem_vfs -> " device="2" writeable="yes" />    
		</config>
		<route>
			<service name="Report"> <child name="ahci_report_rom"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

  <start name="snapper_vfs" ram="200M" caps="200">
    <binary name="vfs"/>
   	<provides><service name="File_system"/></provides>
   	<config>
   		<vfs>
   			<dir name="dev">
   				<block name="block" io_buffer="128"/>
   			</dir>
        <lwext4 block_device="/dev/block" cache_write_back="yes"
              expand_via_io="no" writeable="yes"
              reporting="no"
              external_cache_size="32M" report_cache="yes"/>
   		</vfs>
   		<policy label_prefix="snapper" root="/" writeable="yes"/>
   	</config>
    <route>
      <service name="Block"><child name="ahci"/></service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
  </start>

  <start name="isomem_vfs" ram="200M" caps="200">
    <binary name="vfs"/>
    <provides><service name="File_system"/></provides>
    <config>
      <vfs>
        <rump fs="ext2fs" ram="10M"/>
   	  </vfs>
   	  <policy label_prefix="monitor" root="/" writeable="yes"/>
    </config>
  </start>

  <start name="snapper" ram="400M" caps="100">
    <provides>
      <service name="Snapper"/>
    </provides>

    <config
        verbose="true"
        redundancy="2"
        integrity="true"
        max_snapshots="0"
        min_snapshots="0"
        threshold="1000"
        expiration="3600">

      <rtc/>

      <vfs>
        <fs/>
      </vfs>
    </config>
	<route>
		<service name="Block"><child name="ahci"/></service>
		<service name="File_system"><child name="snapper_vfs"/></service>        
		<any-service> <parent/> <any-child /> </any-service>
	</route>
  </start>

  <start name="terminal" ram="2M">
		<binary name="pc_uart"/>
		<provides>
			<service name="Terminal"/>
			<service name="Uart"/>
		</provides>
		<config>
			<policy label_prefix="monitor" uart="1"/>
		</config>
	</start>

  <start name="monitor" caps="4000" ram="2G">
		<config>
			<parent-provides>
				<service name="LOG"/>
				<service name="PD"/>
				<service name="CPU"/>
        <service name="ROM"/>
        <service name="RM"/>
        <service name="Timer"/>
        <service name="Block"/>
        <service name="Snapper"/>
        <service name="Gui"/>
        <service name="Capture"/>
        <service name="Event"/>
        <service name="File_system"/>
			</parent-provides>
			<default caps="100"/>

			<monitor>
				<policy label="isomem" wait="yes" wx="yes"/>
			</monitor>

    	<start name="isomem" caps="2000">
    		<resource name="RAM" quantum="1G"/>
    
        <config verbose="yes" ld_verbose="yes">
          <vfs>
            <fs/>
          </vfs>
    		</config>
    		<route>
    			<service name="Block"><parent/></service>
					<service name="PD">  <local/> </service>
					<service name="CPU"> <local/> </service>
    			<any-service> <parent/> <any-child /> </any-service>
    		</route>
    	</start>

		</config>
    <route>
      <service name="Block"><child name="ahci"/></service>
    	<service name="File_system"><child name="isomem_vfs"/></service>
      <service name="Terminal"><child name="terminal"/></service>
      <any-service> <parent/> <any-child/> </any-service>
    </route>
	</start>
}

append config [ exec $cat [genode_dir]/repos/ports/run/phantom_gui_drivers-pc.inc ]
append config [ exec $cat [genode_dir]/repos/ports/run/phantom_gui-common.inc ]

append config { </config> }

install_config $config

#
# Boot modules
#
build_boot_image [list {*}[build_artifacts] phantom_classes isomem]

append qemu_args " -smp 8 "
append qemu_args " -m 12000 "
append qemu_args " -device virtio-vga -enable-kvm -cpu host "
append qemu_args " -device ahci,id=ahci -boot d "
append qemu_args " -drive id=disk,file=bin/block0.raw,format=raw,if=none             -device ide-hd,drive=disk,bus=ahci.0 "
append qemu_args " -drive id=snapper,file=bin/snapper_block.raw,format=raw,if=none   -device ide-hd,drive=snapper,bus=ahci.1 "
append qemu_args " -drive id=isomemfs,file=bin/isomem_fs_block.raw,format=raw,if=none   -device ide-hd,drive=isomemfs,bus=ahci.2 " 

set host "localhost"
set port "5555"

append qemu_args " -serial stdio "
append qemu_args " -serial chardev:uart "
append qemu_args " -chardev socket,id=uart,port=$port,host=$host,server=on,wait=off,ipv4=on "

run_genode_until forever

# Local Variables:
# mode: tcl
# End:
