#
# NB This will segfault since PhantomOS is not supported on base-linux!
#

assert_spec x86

create_boot_directory
build {
    core init timer
    driver/rtc
    lib/ld lib/vfs
    server/vfs_block
    lib/vfs_import
    server/vfs
    snapper
    lib/snap
}

#
# Build EXT2-file-system image
#

set mke2fs [installed_command mke2fs]
set dd     [installed_command dd]
catch { exec $dd if=/dev/zero of=bin/snapper_block.raw bs=1M count=16 }
catch { exec $mke2fs -F bin/snapper_block.raw }

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer" priority="0">
		<resource name="RAM" quantum="1M"/>
		<resource name="CPU" quantum="5"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="linux_rtc" ld="no">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Rtc"/>
		</provides>
	</start>

<start name="isomem_block" ram="4G" caps="2000">
  <binary name="vfs_block"/>
	<provides><service name="Block"/></provides>
	<config>
		<vfs>
			<ram/>
			<import>
				<rom name="block0.raw"/>
			</import>
		</vfs>
		<policy label_prefix="isomem"
			      file="/block0.raw" block_size="512" writeable="yes"/>
  </config>
</start>

<start name="snapper_block" ram="4G" caps="2000">
  <binary name="vfs_block"/>
	<provides><service name="Block"/></provides>
	<config>
		<vfs>
			<ram/>
			<import>
				<rom name="snapper_block.raw"/>
			</import>
		</vfs>
		<policy label_prefix="vfs"
			      file="/snapper_block.raw" block_size="512" writeable="yes"/>
  </config>
</start>

<start name="vfs" ram="200M" caps="200">
 	<provides><service name="File_system"/></provides>
 	<config>
 		<vfs>
 			<dir name="dev">
 				<block name="block" block_buffer_count="128"/>
 			</dir>
      <dir name="snapper">
        <ram/>
      </dir>
 		</vfs>
 		<policy label_prefix="snapper" root="/snapper" writeable="yes"/>
 	</config>
 		<route>
 			<service name="Block"><child name="snapper_block"/></service>
 			<any-service> <parent/> <any-child /> </any-service>
 		</route>
</start>

    <start name="snapper" ram="400M" caps="100">
      <provides>
        <service name="Snapper"/>
      </provides>

      <config
          verbose="true"
          redundancy="2"
          integrity="true"
          max_snapshots="0"
          min_snapshots="0"
          threshold="1000"
          expiration="3600">

        <rtc/>

        <vfs>
          <fs/>
        </vfs>
      </config>
    </start>


 	<start name="isomem" caps="2000">
 		<resource name="RAM" quantum="700M"/>
 
 		<config verbose="yes" ld_verbose="yes">
 		</config>
 		<route>
 			<service name="Block"><child name="isomem_block"/></service>
 			<any-service> <parent/> <any-child /> </any-service>
 		</route>
 	</start>
</config> }

#
# Boot modules
#
build_boot_image [list {*}[build_artifacts] phantom_classes isomem block0.raw snapper_block.raw]

run_genode_until forever
